"""init schema

Revision ID: 3f28e8a66ddd
Revises: 
Create Date: 2025-10-29 19:03:58.479157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f28e8a66ddd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_step')
    op.drop_table('offer')
    op.drop_table('company')
    op.drop_table('offer_item')
    op.drop_table('lead')
    op.drop_table('sequence')
    op.drop_table('sequence_run')
    op.drop_table('contact')
    op.drop_table('followup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('due_at', sa.DATETIME(), nullable=False),
    sa.Column('done', sa.BOOLEAN(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sequence_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('current_step', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('offer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('qty', sa.FLOAT(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=200), nullable=False),
    sa.Column('total_net', sa.FLOAT(), nullable=False),
    sa.Column('total_gross', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_step',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sequence_id', sa.INTEGER(), nullable=False),
    sa.Column('order_no', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('wait_days', sa.INTEGER(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
